# Generated by Django 5.0.4 on 2024-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=500)),
                ('SubjectType', models.CharField(max_length=500)),
                ('SubjectId', models.CharField(max_length=500)),
                ('ResearchCenter', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('ResearchCenterId', models.AutoField(primary_key=True, serialize=False)),
                ('ResearchCenterName', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='DataLog',
        ),
    ]
