# Generated by Django 5.0.4 on 2024-05-05 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0002_device_researchcenter_delete_datalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcenter',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now, max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now, max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='ResearchCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadstageServer.researchcenter'),
        ),
    ]
