# Generated by Django 5.0.4 on 2024-05-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0003_rename_device_experiments_devicelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcenters',
            name='ExperimentsList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadstageServer.experiments'),
        ),
    ]
