# Generated by Django 5.0.4 on 2024-05-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0003_researchcenter_dateofjoining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='DateOfJoining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='researchcenter',
            name='DateOfJoining',
            field=models.DateField(),
        ),
    ]
