# Generated by Django 5.0.4 on 2024-05-05 14:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0004_alter_device_dateofjoining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='SubjectId',
        ),
        migrations.RemoveField(
            model_name='device',
            name='SubjectType',
        ),
        migrations.AlterField(
            model_name='device',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='researchcenter',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectId', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField(default=datetime.datetime.now)),
                ('ResearchCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeadstageServer.researchcenter')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='Subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeadstageServer.subject'),
        ),
    ]
