# Generated by Django 5.0.4 on 2024-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0005_remove_device_subjectid_remove_device_subjecttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Subject',
        ),
    ]
