# Generated by Django 5.0.4 on 2024-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeadstageServer', '0006_remove_device_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='device_set', to='HeadstageServer.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='subject_set', to='HeadstageServer.device'),
        ),
    ]
