#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/david/Desktop/WiFi Headstage/WiFiHeadstage V2/Passthrough/promote.xml}
msg_load {C:/Users/david/Desktop/WiFi Headstage/WiFiHeadstage V2/Passthrough/promote.xml}
des_set_project_udb -in {Passthrough_impl_1_syn.udb} -out {Passthrough_impl_1_map.udb} -milestone map -pm ice40tp
map_set_option {pdc_file "C:/Users/david/Desktop/WiFi Headstage/WiFiHeadstage V2/Passthrough/Constrain.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   runtime_log $out
   set ret 1
}
exit -force ${ret}
