    STM32_FIFO u_STM32_FIFO(.clk_i(clk_i),
        .rst_i(rst_i),
        .wr_en_i(wr_en_i),
        .rd_en_i(rd_en_i),
        .wr_data_i(wr_data_i),
        .full_o(full_o),
        .empty_o(empty_o),
        .almost_full_o(almost_full_o),
        .almost_empty_o(almost_empty_o),
        .data_cnt_o(data_cnt_o),
        .rd_data_o(rd_data_o));
