/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.1.288.0
    Soft IP Version: 1.0.1
<<<<<<< HEAD
    2026 05 20 13:40:59
=======
<<<<<<< HEAD
    2026 05 27 13:11:01
=======
    2026 05 20 13:40:59
>>>>>>> 2d0a6dcea4548812d6ef14daab62e7ceae19b447
>>>>>>> ed5c0376b362634e1e81d9a369ec4feb75cb968b
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module CLK_48MHz (ref_clk_i, rst_n_i, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  outcore_o;
    output  outglobal_o;
endmodule